// <auto-generated />
namespace MyClinic_DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Appoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Appoint));
        
        string IMigrationMetadata.Id
        {
            get { return "202403041054502_Appoint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
